version: '3.8'
services:
  react-ui:
    container_name: react-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://nginx:5000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    restart: always  # Talk to NGINX instead of Flask
    networks:
      - web_network  # Must match the API server's network

networks:
  web_network:
    external: true  # Use the same network as Flask/Nginx
