/**
 * Application modules configuration.
 * This file is auto-generated by the backend. Do not edit manually.
 */

export const DASHBOARD_ENABLED = true;
export const PLANNING_ENABLED = true;
export const TODO_LISTS_ENABLED = true;
export const TABLES_ENABLED = true;
export const IMPORT_PRINT_TOOLS_ENABLED = true;
export const COLLARETTO_OPERATIONS_ENABLED = true;
export const OPERATORS_MANAGEMENT_ENABLED = true;
export const SUBCONTRACTOR_MANAGEMENT_ENABLED = true;

