/**
 * Installation-specific configuration for Kanban (cutting room, devices, mappings).
 * This file is auto-generated by the backend. Do not edit manually.
 */

export const INTERNAL_CUTTING_ROOM = 'ZALLI';
export const SPREADER_LINE_COUNT = 3;
export const CUTTER_LINE_COUNT = 2;

export const SPREADER_DEVICES = [
  'SP0',
  'SP1',
  'SP2',
  'SP3',
  'MS',
];

export const CUTTER_DEVICES = [
  'CT1',
  'CT2',
];

export const CUTTER_ASSIGNMENTS = {
  CT1: ['SP1', 'SP2'],
  CT2: ['SP2', 'SP3', 'SP1'],
};
